---
Description: Amazon VPC Reachability Analyzer demo
Parameters: 
  InstanceA: 
    Type: String
  InstanceB: 
    Type: String
  InstanceC: 
    Type: String
Resources:
  NetworkInsightsPathAB:
    Type: AWS::EC2::NetworkInsightsPath
    Properties: 
      Destination: !Ref InstanceB
      Protocol: tcp
      Source: !Ref InstanceA
  NetworkInsightsPathAC:
    Type: AWS::EC2::NetworkInsightsPath
    Properties: 
      Destination: !Ref InstanceC
      Protocol: tcp
      Source: !Ref InstanceA
  NetworkInsightsAnalysisAB:
    Type: AWS::EC2::NetworkInsightsAnalysis
    Properties: 
      NetworkInsightsPathId: !Ref NetworkInsightsPathAB
  NetworkInsightsAnalysisAC:
    Type: AWS::EC2::NetworkInsightsAnalysis
    Properties: 
      NetworkInsightsPathId: !Ref NetworkInsightsPathAC