---
Description: Amazon VPC Reachability Analyzer demo
Resources:
  NetworkInsightsPathAB:
    Type: AWS::EC2::NetworkInsightsPath
    Properties: 
      Destination: 
        Fn::ImportValue: !Sub InstanceB-${AWS::Region} 
      DestinationPort: 22
      Protocol: tcp
      Source: 
        Fn::ImportValue: !Sub InstanceA-${AWS::Region} 
  NetworkInsightsPathAC:
    Type: AWS::EC2::NetworkInsightsPath
    Properties: 
      Destination: 
        Fn::ImportValue: !Sub InstanceC-${AWS::Region} 
      DestinationPort: 22
      Protocol: tcp
      Source: 
        Fn::ImportValue: !Sub InstanceA-${AWS::Region} 
  NetworkInsightsAnalysisAB:
    Type: AWS::EC2::NetworkInsightsAnalysis
    Properties: 
      NetworkInsightsPathId: !Ref NetworkInsightsPathAB
  NetworkInsightsAnalysisAC:
    Type: AWS::EC2::NetworkInsightsAnalysis
    Properties: 
      NetworkInsightsPathId: !Ref NetworkInsightsPathAC