Description: AWS Service Catalog AppRegistry demo
Resources:
  MyAttributeGroup:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties: 
      Attributes:
        {
            Department: "datascience",
            CostCenter: "cc1",
            Team: "salesanalytics"
        }
      Description: "sales analytics"
      Name: "Corp_DataScience_SalesAnalytics"
  MyApplication:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties: 
      Description: "Real Time Rec App"
      Name: "CC_Recommendation_App"
      Tags: 
        Name : RecommendationEngine
        ApplicationId : AppXYZ
        ProductionLine : PR10
        BusinessUnit : BU1
  # MyAttributeGroupAssociation:
  #   Type: AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation
  #   Properties: 
  #     Application: String
  #     AttributeGroup: String
  # MyResourceAssociation:
  #   Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
  #   Properties: 
  #     Application: String
  #     Resource: String
  #     ResourceType: String