Description: AWS Service Catalog AppRegistry demo
Parameters: 
  AttributeGroupName: 
    Description: The attribute group name
    Type: String
    Default: "Corp_DataScience_SalesAnalytics"
  ApplicationName: 
    Description: The name of the Application
    Type: String
    Default: CC_Recommendation_App
  ResourceName: 
    Description: CloudFormation stack name
    Type: String
    Default: aws-5-mins-sqs
Resources:
  MyAttributeGroup:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties: 
      Attributes:
        {
            Department: "datascience",
            CostCenter: "cc1",
            Team: "salesanalytics"
        }
      Description: "sales analytics"
      Name: !Ref AttributeGroupName
  MyApplication:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties: 
      Description: "Real Time Rec App"
      Name: !Ref ApplicationName
      Tags: 
        Name : RecommendationEngine
        ApplicationId : AppXYZ
        ProductionLine : PR10
        BusinessUnit : BU1
  MyAttributeGroupAssociation:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation
    DependsOn: MyApplication
    Properties: 
      Application: !Ref ApplicationName
      AttributeGroup: Corp_DataScience_SalesAnalytics
  MyResourceAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    DependsOn: MyApplication
    Properties: 
      Application: !Ref ApplicationName
      Resource: !Ref ResourceName
      ResourceType: CFN_STACK