Description: AWS Service Catalog AppRegistry demo
Resources:
  MyAttributeGroup:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties: 
      Attributes: 
        Attributes
      Description: String
      Name: String
      Tags: 
        Key : Value
  MyApplication:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties: 
      Description: String
      Name: String
      Tags: 
        Key : Value
  MyAttributeGroupAssociation:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation
    Properties: 
      Application: String
      AttributeGroup: String
  MyResourceAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties: 
      Application: String
      Resource: String
      ResourceType: String