Description: AWS Service Catalog AppRegistry demo
Resources:
  MyAttributeGroup:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties: 
      Attributes:
        {
            Department: "datascience",
            CostCenter: "cc1",
            Team: "salesanalytics"
        }
      Description: "sales analytics"
      Name: "Corp_DataScience_SalesAnalytics"
  MyApplication:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties: 
      Description: "Real Time Rec App"
      Name: CC_Recommendation_App
      Tags: 
        Name : RecommendationEngine
        ApplicationId : AppXYZ
        ProductionLine : PR10
        BusinessUnit : BU1
  MyAttributeGroupAssociation:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation
    DependsOn: MyApplication
    Properties: 
      Application: CC_Recommendation_App
      AttributeGroup: Corp_DataScience_SalesAnalytics
  MyResourceAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    DependsOn: MyApplication
    Properties: 
      Application: CC_Recommendation_App
      Resource: aws-5-mins-sqs
      ResourceType: CFN_STACK